#include <bits/stdc++.h>
using namespace std;

vector<int64_t> divisor(int64_t n)
{
    vector<int64_t> ret;
    for (int64_t i = 1; i * i <= n; i++)
    {
        if (n % i == 0)
        {
            ret.push_back(i);
            if (i * i != n)
            {
                ret.push_back(n / i);
            }
        }
    }
    sort(begin(ret), end(ret));
    return (ret);
}

void solve(long long N)
{
    int cnt = 0;
    for (int k = 1; k <= N; k++)
    {
        if (k % 2 == 1 && divisor(k).size() == 8)
        {
            cnt++;
        }
    }
    cout << cnt << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long N;
    scanf("%lld", &N);
    solve(N);
    return 0;
}
