#include <bits/stdc++.h>
using namespace std;

void solve(long long X, long long A, long long B)
{
    cout << (X - A) % B << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long X;
    scanf("%lld", &X);
    long long A;
    scanf("%lld", &A);
    long long B;
    scanf("%lld", &B);
    solve(X, A, B);
    return 0;
}
