#include <bits/stdc++.h>
using namespace std;

void solve(long long T, long long X)
{
    cout << (double)T / X << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long T;
    scanf("%lld", &T);
    long long X;
    scanf("%lld", &X);
    solve(T, X);
    return 0;
}
