#include <bits/stdc++.h>
using namespace std;

void solve(int N, int X, int Y)
{
    // vector<vector<int>> D(N, vector<int>(N, 0));
    vector<int> A(N, 0);
    for (int i = 1; i <= N - 1; i++)
    {
        for (int j = i + 1; j <= N; j++)
        {
            A[min(abs(i - X) + abs(j - Y) + 1, abs(i - j))]++;
        }
    }

    for (int i = 1; i <= N - 1; i++)
    {
        cout << A[i] << endl;
    }
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long N;
    scanf("%lld", &N);
    long long X;
    scanf("%lld", &X);
    long long Y;
    scanf("%lld", &Y);
    solve(N, X, Y);
    return 0;
}
