#include <bits/stdc++.h>
using namespace std;

void solve(long long N)
{
    cout << static_cast<double>(N + (N % 2)) / static_cast<double>(2 * N) << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long N;
    scanf("%lld", &N);
    solve(N);
    return 0;
}
