#include <bits/stdc++.h>
using namespace std;

void solve(unsigned long long H, unsigned long long W)
{
    unsigned long long hodd = (H - 1) / 2 + 1, heven = H - hodd;
    unsigned long long wodd = (W - 1) / 2 + 1, weven = W - wodd;
    if (H == 1 || W == 1)
    {
        cout << 1 << endl;
    }
    else
    {
        cout << hodd * wodd + heven * weven << endl;
    }
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    unsigned long long H, W;
    cin >> H >> W;
    solve(H, W);
    return 0;
}
