#include <bits/stdc++.h>
using namespace std;

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    string S = "";
    cin >> S;

    list<char> LS;

    for (size_t i = 0; i < S.length(); i++)
    {
        LS.push_back(S[i]);
    }

    long long Q = 0;
    cin >> Q;

    bool isReversed = false;

    for (size_t i = 0; i < Q; i++)
    {
        long long T = 0;
        cin >> T;

        if (T == 1)
        {
            isReversed = !isReversed;
        }
        else
        {
            long long F = 0;
            cin >> F;

            char C = '#';
            cin >> C;

            if (F == 1)
            {

                if (isReversed == false)
                {
                    // S = C + S;
                    LS.push_front(C);
                }
                else
                {
                    // S = S + C;
                    LS.push_back(C);
                }
            }
            else
            {
                if (isReversed == false)
                {
                    // S = S + C;
                    LS.push_back(C);
                }
                else
                {
                    // S = C + S;
                    LS.push_front(C);
                }
            }
        }
    }

    if (!isReversed)
    {
        for (auto it = LS.begin(); it != LS.end(); it++)
        {
            cout << *it;
        }
        cout << endl;
    }
    else
    {
        for (auto it = LS.rbegin(); it != LS.rend(); it++)
        {
            cout << *it;
        }
        cout << endl;
    }

    return 0;
}
