#include <bits/stdc++.h>
using namespace std;

void solve(string S)
{
    if (S[0] == S[1] || S[1] == S[2] || S[2] == S[3])
    {
        cout << "Bad" << endl;
    }
    else
    {
        cout << "Good" << endl;
    }
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    string S;
    cin >> S;
    solve(S);
    return 0;
}
