#include <bits/stdc++.h>
using namespace std;

int searchkk(vector<int> &b)
{
    int val = -1;
    for (int i = b.size() - 1; i >= 0; i--)
    {
        if (b[i] == i + 1)
        {
            val = b[i];
            b.erase(b.begin() + i);
            return val;
        }
    }
    return val;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    int N = 0;
    cin >> N;

    vector<int> b(N, 0);
    for (int i = 0; i < N; i++)
    {
        cin >> b[i];
    }

    vector<int> a(0);
    for (int i = 0; i < N; i++)
    {
        int val = searchkk(b);
        if (val == -1)
        {
            cout << -1 << endl;
            return 0;
        }
        else
        {
            a.push_back(val);
        }
    }

    for (int i = a.size() - 1; i >= 0; i--)
    {
        cout << a[i] << endl;
    }

    return 0;
}
