#include <bits/stdc++.h>
using namespace std;

void solve(long long A, long long B)
{
    if (A + B <= 3)
    {
        cout << A + B << endl;
    }
    else
    {
        cout << max(A - B, B - A) << endl;
    }
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long A;
    scanf("%lld", &A);
    long long B;
    scanf("%lld", &B);
    solve(A, B);
    return 0;
}
