#include <bits/stdc++.h>
using namespace std;

void solve(long long A, long long B, long long C, long long D, long long E, long long F)
{
    vector<int> arr(6, 0);
    arr[0] = A;
    arr[1] = B;
    arr[2] = C;
    arr[3] = D;
    arr[4] = E;
    arr[5] = F;

    sort(arr.begin(), arr.end());

    cout << arr[3] << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long A;
    scanf("%lld", &A);
    long long B;
    scanf("%lld", &B);
    long long C;
    scanf("%lld", &C);
    long long D;
    scanf("%lld", &D);
    long long E;
    scanf("%lld", &E);
    long long F;
    scanf("%lld", &F);
    solve(A, B, C, D, E, F);
    return 0;
}
