#include <bits/stdc++.h>
using namespace std;

void solve(long long N, std::vector<long long> d)
{
    vector<long long> d2(N, 0);
    for (size_t i = 0; i < N; i++)
    {
        d2[i] = d[i] * d[i];
    }

    long long sum1 = 0LL, sum2 = 0LL;
    for (size_t i = 0; i < N; i++)
    {
        sum1 += d[i];
        sum2 += d2[i];
    }

    cout << (sum1 * sum1 - sum2) / 2LL << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long N;
    scanf("%lld", &N);
    std::vector<long long> d(N);
    for (int i = 0; i < N; i++)
    {
        scanf("%lld", &d[i]);
    }
    solve(N, std::move(d));
    return 0;
}
