#include <bits/stdc++.h>
using namespace std;

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    int N = 0;
    cin >> N;

    vector<int> A(N, 0);
    for (size_t i = 0; i < N; i++)
    {
        cin >> A[i];
    }

    bool approved = true;
    for (size_t i = 0; i < N; i++)
    {
        if ((A[i] % 2 == 1 || (A[i] % 3 != 0 && A[i] % 5 != 0)) && A[i] % 2 == 0)
        {
            approved = false;
            break;
        }
    }

    cout << (approved ? "APPROVED" : "DENIED") << endl;

    return 0;
}
