#include <bits/stdc++.h>
using namespace std;

void solve(long long A, long long B, long long C)
{
    vector<int> a(0);
    a.push_back(A);
    a.push_back(B);
    a.push_back(C);
    sort(a.begin(), a.end());

    cout << a[2] * 10 + a[1] + a[0] << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long A;
    scanf("%lld", &A);
    long long B;
    scanf("%lld", &B);
    long long C;
    scanf("%lld", &C);
    solve(A, B, C);
    return 0;
}
