#include <bits/stdc++.h>
using namespace std;

void solve(long long N, long long R)
{
    cout << (R + 100 * max(10LL - N, 0LL)) << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long N;
    scanf("%lld", &N);
    long long R;
    scanf("%lld", &R);
    solve(N, R);
    return 0;
}
