#include <bits/stdc++.h>
using namespace std;

void solve(long long A, long long B, long long C, long long X, long long Y)
{
    long long res = 1000000009;

    for (long long k = 0; k <= max(X, Y); k++)
    {
        res = min(res, 2 * C * k + A * max(0LL, X - k) + B * max(0LL, Y - k));
    }

    cout << res << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long A;
    scanf("%lld", &A);
    long long B;
    scanf("%lld", &B);
    long long C;
    scanf("%lld", &C);
    long long X;
    scanf("%lld", &X);
    long long Y;
    scanf("%lld", &Y);
    solve(A, B, C, X, Y);
    return 0;
}
