#include <bits/stdc++.h>
using namespace std;

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    int ab = 0, bc = 0, ca = 0;
    cin >> ab >> bc >> ca;

    cout << (double)(ab * bc / 2) << endl;
    return 0;
}
