#include <bits/stdc++.h>
using namespace std;

long long gcm(long long A, long long B)
{
    if (B == 0)
    {
        return A;
    }
    else
    {
        return gcm(B, A % B);
    }
}

void solve(long long A, long long B)
{
    cout << (A * B) / gcm(A, B) << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long A;
    scanf("%lld", &A);
    long long B;
    scanf("%lld", &B);
    solve(A, B);
    return 0;
}
