#include <bits/stdc++.h>
using namespace std;

const string YES = "Yes";
const string NO = "No";

void solve(std::string S)
{
    bool type1 = (S[0] == S[1] && S[2] == S[3]);
    bool type2 = (S[0] == S[2] && S[1] == S[3]);
    bool type3 = (S[0] == S[3] && S[1] == S[2]);
    bool type0 = (S[0] == S[1] && S[1] == S[2] && S[2] == S[3]);

    cout << (((type1 || type2 || type3) && (!type0)) ? YES : NO) << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    std::string S;
    std::cin >> S;
    solve(S);
    return 0;
}
