#include <bits/stdc++.h>
using namespace std;

const string YES = "Yes";
const string NO = "No";

void solve(string N)
{
    cout << (N[0] == '7' || N[1] == '7' || N[2] == '7' ? YES : NO) << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    string N;
    cin >> N;
    solve(N);
    return 0;
}
