#include <bits/stdc++.h>
using namespace std;

void solve(long long a, long long b, long long x)
{
    long double res = 0.0;
    if (a * a * b < 2 * x)
    {
        long double height = 2.0 * static_cast<long double>(a * a * b - x) / static_cast<long double>(a * a);
        res = (180.0000000 / 3.141592653589793238462643383279) * atan(height / static_cast<long double>(a));
    }
    else
    {
        long double width = 2.0 * static_cast<long double>(x) / static_cast<long double>(a * b);
        res = (180.0000000 / 3.141592653589793238462643383279) * atan(static_cast<long double>(b) / width);
    }
    cout << setprecision(10) << res << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long a;
    scanf("%lld", &a);
    long long b;
    scanf("%lld", &b);
    long long x;
    scanf("%lld", &x);
    solve(a, b, x);
    return 0;
}
