#include <bits/stdc++.h>
using namespace std;

void solve(long long N, std::vector<long long> a)
{
    long long k = 1, d = 0;
    for (size_t i = 0; i < N; i++)
    {
        if (a[i] == k)
        {
            k++;
            // cout << "k = " << k << ", ";
        }
        else
        {
            d++;
            // cout << "d = " << d << ", ";
        }
        // cout << "i = " << i << endl;
    }
    cout << (k == 1 ? (-1) : d) << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long N;
    scanf("%lld", &N);
    std::vector<long long> a(N);
    for (int i = 0; i < N; i++)
    {
        scanf("%lld", &a[i]);
    }
    solve(N, std::move(a));
    return 0;
}
