#include <bits/stdc++.h>
using namespace std;

void solve(long long D)
{
    cout << "Christmas";
    for (size_t i = 0; i < 25 - D; i++)
    {
        cout << " Eve";
    }
    cout << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long D;
    scanf("%lld", &D);
    solve(D);
    return 0;
}
