#include <bits/stdc++.h>
using namespace std;

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    string s;
    cin >> s;

    cout << stoi(s.substr(0, 1)) + stoi(s.substr(1, 1)) + stoi(s.substr(2, 1)) << endl;

    return 0;
}
