#include <bits/stdc++.h>
using namespace std;

void solve(std::string S, std::string T)
{
    int cnt = 0;
    for (size_t i = 0; i < 3; i++)
    {
        if (S[i] == T[i])
        {
            cnt++;
        }
    }
    cout << cnt << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    std::string S;
    std::cin >> S;
    std::string T;
    std::cin >> T;
    solve(S, T);
    return 0;
}
