#include <bits/stdc++.h>
using namespace std;

int ctoi(char c)
{
    int res = static_cast<int>(c - '0');
    return (0 <= res && res <= 9 ? res : -1);
}

char itoc(int i)
{
    return (0 <= i && i <= 9 ? static_cast<char>(i) + '0' : 'X');
}

void solve(std::string S)
{
    if (ctoi(S[0]) == -1 || ctoi(S[1]) == -1 || ctoi(S[2]) == -1)
    {
        cout << "error" << endl;
    }
    else
    {
        cout << 2 * stoi(S) << endl;
    }
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    std::string S;
    std::cin >> S;
    solve(S);
    return 0;
}
