#include <bits/stdc++.h>
using namespace std;

void solve(std::string S)
{
    S = "X" + S + "X";
    string S0 = "ATGC";

    vector<int> l(0), r(0);
    for (int i = 1; i < S.length(); i++)
    {
        if (S0.find(S[i]) != string::npos && S0.find(S[i - 1]) == string::npos)
        {
            l.push_back(i);
        }
        else if (S0.find(S[i]) == string::npos && S0.find(S[i - 1]) != string::npos)
        {
            r.push_back(i);
        }
    }

    int m = 0;
    for (int i = 0; i < l.size(); i++)
    {
        // cout << l[i] << " " << r[i] << endl;
        m = max(m, r[i] - l[i]);
    }
    cout << m << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    std::string S;
    std::cin >> S;
    solve(S);
    return 0;
}
