#include <bits/stdc++.h>
using namespace std;

void solve(long long N)
{
    cout << (1 + N) * N / 2 - ((1 + (N / 3)) * (N / 3) / 2) * 3 - ((1 + (N / 5)) * (N / 5) / 2) * 5 + ((1 + (N / 15)) * (N / 15) / 2) * 15 << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long N;
    scanf("%lld", &N);
    solve(N);
    return 0;
}
