#include <bits/stdc++.h>
using namespace std;

void solve(long long N, std::string S)
{
    string T(S.length(), 'A');
    int A = static_cast<int>('A');
    for (size_t i = 0; i < S.length(); i++)
    {
        T[i] = static_cast<char>((static_cast<int>(S[i]) - A + N) % 26 + A);
    }

    cout << T << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long N;
    scanf("%lld", &N);
    std::string S;
    std::cin >> S;
    solve(N, S);
    return 0;
}
