#include <bits/stdc++.h>
using namespace std;

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    int N = 0, Q = 0;
    string S = "";

    cin >> N >> S >> Q;

    map<char, set<int>> area;
    for (size_t i = 0; i < S.length(); i++)
    {
        area[S[i]].insert(i);
    }

    for (int i = 0; i < Q; i++)
    {
        int type = 0;
        cin >> type;
        if (type == 1)
        {
            int iq = 0;
            char c = '#';
            cin >> iq >> c;
            iq--;

            area[S[iq]].erase(iq);
            S[iq] = c;
            area[S[iq]].insert(iq);
        }
        else
        {
            int l = 0, r = 0;
            cin >> l >> r;
            l--;
            r--;

            int cnt = 0;
            for (int j = 0; j < 26; j++)
            {
                auto it = area['a' + j].lower_bound(l);
                if (it != area['a' + j].end() && *it <= r)
                {
                    cnt++;
                }
            }
            cout << cnt << endl;
        }
    }

    return 0;
}
