#include <bits/stdc++.h>
using namespace std;

void solve(std::string S)
{
    int y = stoi(S.substr(0, 4));
    int m = stoi(S.substr(5, 2));
    int d = stoi(S.substr(8, 2));

    if (y < 2019)
    {
        cout << "Heisei" << endl;
    }
    else if (y == 2019 && m < 4)
    {
        cout << "Heisei" << endl;
    }
    else if (y == 2019 && m == 4 && d <= 30)
    {
        cout << "Heisei" << endl;
    }
    else
    {
        cout << "TBD" << endl;
    }
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    std::string S;
    std::cin >> S;
    solve(S);
    return 0;
}
