#include <bits/stdc++.h>
using namespace std;

void solve(long long N, std::string S, std::string T)
{
    for (size_t i = 0; i < N; i++)
    {
        cout << S[i] << T[i];
    }
    cout << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long N;
    scanf("%lld", &N);
    std::string S;
    std::cin >> S;
    std::string T;
    std::cin >> T;
    solve(N, S, T);
    return 0;
}
