#include <bits/stdc++.h>
using namespace std;

void solve(long long N, std::string S)
{
    long long nr = 0, ng = 0, nb = 0;
    for (size_t i = 0; i < S.length(); i++)
    {
        if (S[i] == 'R')
        {
            nr++;
        }
        else if (S[i] == 'G')
        {
            ng++;
        }
        else
        {
            nb++;
        }
    }

    long long res = nr * ng * nb;

    for (size_t h = 1; h < S.length() / 2 + 1; h++)
    {
        for (size_t i = 0; i + 2 * h < S.length(); i++)
        {
            int j = i + h;
            int k = i + 2 * h;

            if (S[i] == 'R' && S[j] == 'G' && S[k] == 'B')
            {
                res--;
            }

            if (S[i] == 'R' && S[j] == 'B' && S[k] == 'G')
            {
                res--;
            }

            if (S[i] == 'G' && S[j] == 'R' && S[k] == 'B')
            {
                res--;
            }

            if (S[i] == 'G' && S[j] == 'B' && S[k] == 'R')
            {
                res--;
            }

            if (S[i] == 'B' && S[j] == 'R' && S[k] == 'G')
            {
                res--;
            }

            if (S[i] == 'B' && S[j] == 'G' && S[k] == 'R')
            {
                res--;
            }
        }
    }

    cout << res << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long N;
    scanf("%lld", &N);
    std::string S;
    std::cin >> S;
    solve(N, S);
    return 0;
}
