#include <bits/stdc++.h>
using namespace std;

void solve(std::string C)
{
    cout << static_cast<char>(C[0] + 1) << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    std::string C;
    std::cin >> C;
    solve(C);
    return 0;
}
