#include <bits/stdc++.h>
using namespace std;

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    int n = 0;
    cin >> n;

    if (n == 1)
    {
        cout << "Hello World" << endl;
    }
    else
    {
        int a = 0, b = 0;
        cin >> a >> b;
        cout << (a + b) << endl;
    }
    return 0;
}
