#include <bits/stdc++.h>
using namespace std;

void solve(long long M)
{
    cout << (48 - M) << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long M;
    scanf("%lld", &M);
    solve(M);
    return 0;
}
