#include <bits/stdc++.h>
using namespace std;

void solve(long long N, std::vector<long long> A)
{
    vector<long long> B(N + 1, 0);
    for (size_t i = 1; i <= N; i++)
    {
        B[A[i]] = i;
    }

    // for (size_t i = 1; i <= N; i++)
    // {
    //     cout << B[i] << (i == N ? "\n" : " ");
    // }
    // cout << flush;
    for (size_t i = 1; i <= N - 1; i++)
    {
        cout << B[i] << " ";
    }
    cout << B[N] << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long N;
    scanf("%lld", &N);
    std::vector<long long> A(N + 1);
    for (int i = 1; i <= N; i++)
    {
        scanf("%lld", &A[i]);
    }
    solve(N, std::move(A));
    return 0;
}
