#include <bits/stdc++.h>
using namespace std;

void solve(std::string S)
{
    int cnt = 0;
    for (size_t i = 0; i < S.length(); i++)
    {
        if (S[i] == 'o')
        {
            cnt++;
        }
    }
    cout << 700 + 100 * cnt << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    std::string S;
    std::cin >> S;
    solve(S);
    return 0;
}
