#include <bits/stdc++.h>
using namespace std;

void solve(std::string S)
{
    if (S == "SUN")
    {
        cout << 7 << endl;
    }
    else if (S == "MON")
    {
        cout << 6 << endl;
    }
    else if (S == "TUE")
    {
        cout << 5 << endl;
    }
    else if (S == "WED")
    {
        cout << 4 << endl;
    }
    else if (S == "THU")
    {
        cout << 3 << endl;
    }
    else if (S == "FRI")
    {
        cout << 2 << endl;
    }
    else if (S == "SAT")
    {
        cout << 1 << endl;
    }
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    std::string S;
    std::cin >> S;
    solve(S);
    return 0;
}
