#include <bits/stdc++.h>
using namespace std;

void solve(long long N, std::vector<std::string> S)
{
    map<string, int> mp;
    for (auto x : S)
    {
        mp[x] = 0;
    }

    int mx = 0;
    for (auto x : S)
    {
        mp[x]++;
        mx = max(mx, mp[x]);
    }

    for (auto x : mp)
    {
        if (x.second == mx)
        {
            cout << x.first << endl;
        }
    }
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long N;
    scanf("%lld", &N);
    std::vector<std::string> S(N);
    for (int i = 0; i < N; i++)
    {
        std::cin >> S[i];
    }
    solve(N, std::move(S));
    return 0;
}
