#include <bits/stdc++.h>

using namespace std;
using ll = long long;
using P = pair<int, int>;

// GCD, LCM
// https://youtu.be/8lm8o8L9Bmw?t=2285
// https://youtu.be/XI8exXVxZ-Q?t=3595
// https://youtu.be/F2p_e6iKxnk?t=843
ll gcd(ll a, ll b) { return b ? gcd(b, a % b) : a; }
ll lcm(ll a, ll b) { return a / gcd(a, b) * b; }

void solve(long long K)
{
    ll res = 0;
    for (size_t i = 1; i <= K; i++)
    {
        for (size_t j = 1; j <= K; j++)
        {
            for (size_t k = 1; k <= K; k++)
            {
                res += gcd(gcd(i, j), k);
            }
        }
    }
    cout << res << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long K;
    scanf("%lld", &K);
    solve(K);
    return 0;
}
