#include <bits/stdc++.h>
using namespace std;

void solve(std::string b)
{
    if (b == "A")
    {
        cout << "T" << endl;
    }
    else if (b == "T")
    {
        cout << "A" << endl;
    }
    else if (b == "G")
    {
        cout << "C" << endl;
    }
    else if (b == "C")
    {
        cout << "G" << endl;
    }
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    std::string b;
    std::cin >> b;
    solve(b);
    return 0;
}
