#include <bits/stdc++.h>
using namespace std;

void solve(long long r)
{
    cout << (3 * r * r) << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long r;
    scanf("%lld", &r);
    solve(r);
    return 0;
}
