#include <bits/stdc++.h>
using namespace std;

void solve(long long a, std::string s)
{
    if (a >= 3200)
    {
        cout << s << endl;
    }
    else
    {
        cout << "red" << endl;
    }
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long a;
    scanf("%lld", &a);
    std::string s;
    std::cin >> s;
    solve(a, s);
    return 0;
}
