#include <bits/stdc++.h>
using namespace std;

long long gcd(long long A, long long B)
{
    if (B == 0)
    {
        return A;
    }
    else
    {
        return gcd(B, A % B);
    }
}

void solve(long long A, long long B)
{
    const long long GCD = gcd(A, B);

    long long rem = GCD, num_prime = 0;
    for (long long i = 2; i * i <= rem; i++)
    {
        if (rem % i != 0)
        {
            continue;
        }
        else
        {
            while (rem % i == 0)
            {
                rem /= i;
            }
            num_prime++;
        }
    }
    cout << (rem == 1 ? (num_prime + 1) : (num_prime + 2)) << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long A;
    scanf("%lld", &A);
    long long B;
    scanf("%lld", &B);
    solve(A, B);
    return 0;
}
