#include <bits/stdc++.h>
using namespace std;

void solve(std::vector<std::string> c)
{
    cout << c[0].substr(0, 1) << c[1].substr(1, 1) << c[2].substr(2, 1) << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    std::vector<std::string> c(3);
    for (int i = 0; i < 3; i++)
    {
        std::cin >> c[i];
    }
    solve(std::move(c));
    return 0;
}
