#include <bits/stdc++.h>
using namespace std;

void solve(long long N, std::vector<long long> A)
{
    for (size_t i = 1; i < N; i++)
    {
        if (A[i] == A[i - 1])
        {
            cout << "stay" << endl;
        }
        else if (A[i] >= A[i - 1])
        {
            cout << "up " << A[i] - A[i - 1] << endl;
        }
        else
        {
            cout << "down " << A[i - 1] - A[i] << endl;
        }
    }
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long N;
    scanf("%lld", &N);
    std::vector<long long> A(N);
    for (int i = 0; i < N; i++)
    {
        scanf("%lld", &A[i]);
    }
    solve(N, std::move(A));
    return 0;
}
