#include <bits/stdc++.h>
using namespace std;

void solve(long long N)
{   
    long long res = 0, den = 10;
    if (N % 2 == 1) {
        res = 0;
    } else if (N == 0) {
        res = 0;
    } else {
        while(den <= N) {
            res += static_cast<long long>(N / den);
            den *= 5;
        }
    }
    cout << res << endl;
}

void solve2(long long N)
{
    long long res = 0;
    long long M = 0;
    while (N >= 10)
    {
        M = N;
        while (M % 10 == 0 && M > 1)
        {
            res += 1;
            M = M / 10;
        }
        N = N - 2;
    }
    cout << res << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long N;
    scanf("%lld", &N);
    solve(N);
    // solve2(N);
    return 0;
}
