#include <bits/stdc++.h>
using namespace std;

void solve(std::string S, std::string T, long long A, long long B, std::string U)
{
    if (U == S)
    {
        cout << (A - 1) << " " << B << endl;
    }
    else
    {
        cout << A << " " << (B - 1) << endl;
    }
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    std::string S;
    std::cin >> S;
    std::string T;
    std::cin >> T;
    long long A;
    scanf("%lld", &A);
    long long B;
    scanf("%lld", &B);
    std::string U;
    std::cin >> U;
    solve(S, T, A, B, U);
    return 0;
}
