#include <bits/stdc++.h>
using namespace std;

void solve(long long K, long long N, std::vector<long long> A)
{
    vector<long long> B(N, 0);
    for (int i = 0; i < N - 1; i++)
    {
        B[i] = A[i + 1] - A[i];
    }
    B[N - 1] = K + A[0] - A[N - 1];
    sort(B.begin(), B.end());

    cout << K - B[N - 1] << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long K;
    scanf("%lld", &K);
    long long N;
    scanf("%lld", &N);
    std::vector<long long> A(N);
    for (int i = 0; i < N; i++)
    {
        scanf("%lld", &A[i]);
    }
    solve(K, N, std::move(A));
    return 0;
}
