#include <bits/stdc++.h>
using namespace std;

void solve(long long N, long long M, std::vector<std::vector<long long>> A)
{
    long long m = 0;

    for (int i = 0; i < M; i++)
    {
        for (int j = i + 1; j < M; j++)
        {
            long long sum = 0;
            for (int k = 0; k < N; k++)
            {
                sum += max(A[k][i], A[k][j]);
            }
            m = max(m, sum);
        }
    }

    cout << m << endl;
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long N;
    scanf("%lld", &N);
    long long M;
    scanf("%lld", &M);
    std::vector<std::vector<long long>> A(N, std::vector<long long>(M));
    for (int i = 0; i < N; i++)
    {
        for (int j = 0; j < M; j++)
        {
            scanf("%lld", &A[i][j]);
        }
    }
    solve(N, M, std::move(A));
    return 0;
}
